---
- name: configure hostname, domain name, and nameserver
  hosts: network
  gather_facts: no
  vars:
    junos_template: j2/junos-hn-dn-ns.j2
    ios_template: j2/ios-hn-dn-ns.j2
  tasks:

  - name: read from template, configure IOS device
    cisco.ios.ios_config:
      src: "{{ ios_template }}"
    when: ansible_network_os == 'cisco.ios.ios'

  - name: enable netconf service on port 36000
    junipernetworks.junos.junos_netconf:
      listens_on: 36000
      state: present
    when: ansible_network_os == 'junipernetworks.junos.junos'

  - name: change ansible connection to netconf
    set_fact:
      ansible_connection: ansible.netcommon.netconf
    when: ansible_network_os == 'junipernetworks.junos.junos'

  - name: read from template, configure JUNOS device
    junipernetworks.junos.junos_config:
      src: "{{ junos_template }}"
    when: ansible_network_os == 'junipernetworks.junos.junos'
