---
- name: a play that exposes the current access vars
  hosts: network
  gather_facts: no

  tasks:

  - name: show the value of key variables
    debug:
      msg: >
        host: {{ inventory_hostname }},
        con: {{ ansible_connection }},
        nos: {{ ansible_network_os }},
        user: {{ ansible_user }},
        pass: {{ ansible_ssh_pass }}

  - name: "verify access to {{ inventory_hostname }}"
    ping:
    register: ping_response

  - name: debug
    debug:
      msg: "{{ ping_response }}"
 
  - name: assert that the response contains the string 'pong'
    assert:
      that: ping_response.ping == "pong"
