---
- name: a play that verifies access to members of host group 'all'
  hosts: network
  gather_facts: no
 
  tasks:
  
  - name: "verify access to {{ inventory_hostname }}"
    ping:
    register: ping_response

  - name: debug
    debug:
      msg: "{{ ping_response }}"
 
  - name: assert that the response contains the string 'pong'
    assert:
      that: ping_response.ping == "pong"

